export const MOBILITY_ACTIONS = {
  SET_OBJECT: "SET_OBJECT",
  CLEAR_OBJECT: "CLEAR_OBJECT",
  SET_ARRAY: "SET_ARRAY",
  CLEAR_ARRAY: "CLEAR_ARRAY",
  SET_LOADING: "SET_LOADING",
  CLEAR_LOADING: "CLEAR_LOADING",
};
